// A screen that alows coache and owners create classes and sends it to the database
import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:supabase_flutter/supabase_flutter.dart';

class AppColors {
  static const primaryBlue = Color(0xFFDD886C);
  static const linkBlue = Color(0xFFC96E6E);
  static const fieldFill = Color(0xFFF1F3F6);
  static const background = Color(0xFFFFFDE2);
}

// Classes schema: 

// create table public.classes (
//   id bigint generated by default as identity not null,
//   created_at timestamp with time zone not null default now(),
//   class_name text null default ''''''::text,
//   coach_assigned json null default '{}'::json,
//   date date null default now(),
//   time time without time zone null default now(),
//   difficulty numeric null default '0'::numeric,
//   reccuring boolean null default false,
//   registered_users json null default '{}'::json,
//   type_of_class numeric null default '0'::numeric,
//   constraint classes_pkey primary key (id)
// ) TABLESPACE pg_default;

class CreateClassesPage extends StatefulWidget {
  const CreateClassesPage({super.key});

  @override
  State<CreateClassesPage> createState() => _CreateClassesPageState();
}

class _CreateClassesPageState extends State<CreateClassesPage> {
  final SupabaseClient _supabase = Supabase.instance.client;

  final TextEditingController _classNameController = TextEditingController();
  final TextEditingController _coachAssignedController = TextEditingController();
  final TextEditingController _dateController = TextEditingController();
  final TextEditingController _timeController = TextEditingController();
  final TextEditingController _difficultyController = TextEditingController();
  final TextEditingController _recurringController = TextEditingController();
  final TextEditingController _typeOfClassController = TextEditingController();
  final TextEditingController _registeredUsersController = TextEditingController();

  @override
  void dispose() {
    _classNameController.dispose();
    _coachAssignedController.dispose();
    _dateController.dispose();
    _timeController.dispose();
    _difficultyController.dispose();
    _recurringController.dispose();
    _typeOfClassController.dispose();
    _registeredUsersController.dispose();
    super.dispose();
  }

  Future<void> _createClass() async {
    final className = _classNameController.text.trim();
    final coachAssigned = _coachAssignedController.text.trim();
    final date = _dateController.text.trim();
    final time = _timeController.text.trim();
    final difficulty = int.tryParse(_difficultyController.text.trim()) ?? 0;
    final recurring = _recurringController.text.trim().toLowerCase() == 'false';
    final typeOfClass = int.tryParse(_typeOfClassController.text.trim()) ?? 0;
    final registeredUsersText = _registeredUsersController.text.trim();
    
    // Parse registered users as JSON
    Map<String, dynamic>? registeredUsers;
    if (registeredUsersText.isNotEmpty) {
      try {
        registeredUsers = jsonDecode(registeredUsersText) as Map<String, dynamic>;
      } catch (e) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Invalid JSON format for registered users')),
        );
        return;
      }
    } else {
      // Default empty JSON object
      registeredUsers = {};
    }

    if (className.isEmpty || coachAssigned.isEmpty || date.isEmpty || time.isEmpty || difficulty < 0 || typeOfClass < 0) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Please fill out all required fields')),
      );
      return;
    }

    try {
      await _supabase.from('classes').insert({
        'class_name': className,
        'coach_assigned': coachAssigned,
        'date': date,
        'time': time,
        'difficulty': difficulty,
        'reccuring': recurring,
        'type_of_class': typeOfClass,
        'registered_users': registeredUsers, // Now a JSON object
      });

      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Class created successfully')),
      );

      _classNameController.clear();
      _coachAssignedController.clear();
      _dateController.clear();
      _timeController.clear();
      _difficultyController.clear();
      _recurringController.clear();
      _typeOfClassController.clear();
      _registeredUsersController.clear();
    } catch (e) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text('Error creating class: $e')),
      );
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.background,
      ),
      body: SafeArea(
        child: SingleChildScrollView(
          padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 24),
          child: Center(
            child: ConstrainedBox(
              constraints: const BoxConstraints(maxWidth: 320),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.center,
                mainAxisSize: MainAxisSize.min,
            children: [
              const SizedBox(height: 8),
              const Center(
                child: Text(
                  'Create New Class',
                  style: TextStyle(
                    fontSize: 28,
                    fontWeight: FontWeight.w700,
                  ),
                ),
              ),
              const SizedBox(height: 32),

              // Class Name
              SizedBox(
                width: 320,
                child: TextField(
                  controller: _classNameController,
                  decoration: const InputDecoration(labelText: 'Class Name'),
                  textInputAction: TextInputAction.next,
                ),
              ),
              const SizedBox(height: 32),

              // Coach Assigned
              SizedBox(
                width: 320,
                child: TextField(
                  controller: _coachAssignedController,
                  decoration: const InputDecoration(labelText: 'Coach Assigned'),
                  textInputAction: TextInputAction.next,
                ),
              ),
              const SizedBox(height: 32),

              // Date
              SizedBox(
                width: 320,
                child: TextField(
                  controller: _dateController,
                  decoration: const InputDecoration(labelText: 'Date (MM-DD-YYYY)'),
                  textInputAction: TextInputAction.next,
                ),
              ),
              const SizedBox(height: 32),

              // Time
              SizedBox(
                width: 320,
                child: TextField(
                  controller: _timeController,
                  decoration: const InputDecoration(labelText: 'Time (HH:MM)'),
                  textInputAction: TextInputAction.next,
                ),
              ),
              const SizedBox(height: 32),

              // Difficulty
              SizedBox(
                width: 320,
                child: TextField(
                  controller: _difficultyController,
                  decoration: const InputDecoration(labelText: 'Difficulty (0-5)'),
                  keyboardType: TextInputType.number,
                  textInputAction: TextInputAction.next,
                ),
              ),
              const SizedBox(height: 32),

              // Recurring
              SizedBox(
                width: 320,
                child: TextField(
                  controller: _recurringController,
                  decoration: const InputDecoration(labelText: 'Recurring (true/false)'),
                  textInputAction: TextInputAction.next,
                ),
              ),
              const SizedBox(height: 32),

              // Type of Class helper text
              Container(
                width: 320,
                padding: const EdgeInsets.all(12),
                decoration: BoxDecoration(
                  color: Colors.grey[100],
                  borderRadius: BorderRadius.circular(8),
                ),
                child: Text(
                  'Class Types: 1 = TaeKwonDo, 2 = Hapkido, 3 = Judo, 4 = Karate, 5 = Other',
                  style: TextStyle(
                    fontSize: 12,
                    color: Colors.black87,
                  ),
                  textAlign: TextAlign.center,
                ),
              ),
              const SizedBox(height: 16),

              // Type of Class
              SizedBox(
                width: 320,
                child: TextField(
                  controller: _typeOfClassController,
                  decoration: const InputDecoration(labelText: 'Type of Class (1-5)'),
                  keyboardType: TextInputType.number,
                  textInputAction: TextInputAction.next,
                ),
              ),
              const SizedBox(height: 32),

              // Submit Button
              SizedBox(
                width: 320,
                height: 48,
                child: ElevatedButton(
                  onPressed: _createClass,
                  style: ElevatedButton.styleFrom(
                    backgroundColor: AppColors.primaryBlue,
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(8),
                    ),
                  ),
                  child: const Text(
                    'Create Class',
                    style: TextStyle(
                      fontSize: 16,
                      fontWeight: FontWeight.w600,
                    ),
                  ),
                ),
              ),
            ],
              ),
            ),
          ),
        ),
      ),
    );
  }
}