-- 006_masteries_and_mappings.sql
-- Create masteries and mapping tables: a mastery is a collection of goals

CREATE TABLE IF NOT EXISTS public.masteries (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  description text,
  created_at timestamptz NOT NULL DEFAULT timezone('utc', now())
);

CREATE TABLE IF NOT EXISTS public.mastery_goals (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mastery_id bigint NOT NULL REFERENCES public.masteries(id) ON DELETE CASCADE,
  goal_id bigint NOT NULL REFERENCES public.class_goals(id) ON DELETE CASCADE,
  sort_order integer DEFAULT 100,
  created_at timestamptz NOT NULL DEFAULT timezone('utc', now())
);

ALTER TABLE public.masteries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mastery_goals ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public can read masteries" ON public.masteries FOR SELECT USING (true);
CREATE POLICY "Public can read mastery_goals" ON public.mastery_goals FOR SELECT USING (true);

GRANT SELECT ON public.masteries TO authenticated;
GRANT SELECT ON public.mastery_goals TO authenticated;
