-- 007_goals_and_links.sql
-- Create global goals and mapping table so multiple classes can increment the same goal

CREATE TABLE IF NOT EXISTS public.goals (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key text UNIQUE,
  title text NOT NULL,
  description text,
  required_sessions integer DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT timezone('utc', now())
);

CREATE TABLE IF NOT EXISTS public.class_goal_links (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  class_id bigint NOT NULL REFERENCES public.classes(id) ON DELETE CASCADE,
  goal_id bigint NOT NULL REFERENCES public.goals(id) ON DELETE CASCADE,
  sort_order integer DEFAULT 100,
  created_at timestamptz NOT NULL DEFAULT timezone('utc', now()),
  CONSTRAINT unique_class_goal UNIQUE (class_id, goal_id)
);

ALTER TABLE public.goals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.class_goal_links ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public can read goals" ON public.goals FOR SELECT USING (true);
CREATE POLICY "Public can read class_goal_links" ON public.class_goal_links FOR SELECT USING (true);

GRANT SELECT ON public.goals TO authenticated;
GRANT SELECT ON public.class_goal_links TO authenticated;

-- Example insert (run in SQL editor to seed):
-- INSERT INTO public.goals (key, title, description, required_sessions) VALUES ('fighting_skills','Fighting Skills','Improve stand-up fighting skills',8);
-- INSERT INTO public.class_goal_links (class_id, goal_id) VALUES ((SELECT id FROM public.classes WHERE class_name='Warrior Intermediate' LIMIT 1),(SELECT id FROM public.goals WHERE key='fighting_skills' LIMIT 1));
